//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPDFUploader
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Article
    {
        public int FileId { get; set; }

        [Required(AllowEmptyStrings =false,ErrorMessage = "Filename is required.")]
        public string FileName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage ="Please select your file.")]
        public string File { get; set; }
    }
}
